products:
  - name: test-cmd-tool
    quota: 1000,
    quotaInterval: 1,
    quotaTimeUnit: minute,
    description: |
      test-cmd-tool2
    environments:
      - test
    proxies:
      - apigee-account-proxy-v1
